baseurl = "https://cjt-jackton.github.io/"
title = "Chinese tea ~ ä¸Šæµ·çº¢èŒ¶é¦†"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "CJT"
    info = "I set out to do something I love."
    description = "CJT's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    footercontent = "ğŸ° is a lie."

    dateformat = "January 2, 2006"

    hidecredits = false
    hidecopyright = false
    since = 2020

    rtl = false

    colorscheme = "dark"

    math = true

    custom_css = [ "/css/particles.css" ]
    custom_js = [ "/js/particles.js", "/js/app.js" ]

    disqusShortname = ""

 [params.utteranc]
    enable = false
    repo = "CJT-Jackton/CJT-Jackton.github.io-HUGO"
    theme = "github-dark"
    issueTerm = "pathname"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/cjt-jackton/"
[[params.social]]
    name = "Steam"
    icon = "fab fa-steam-symbol fa-2x"
    weight = 2
    url = "https://steamcommunity.com/id/CJT-Jackton"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/CJT____________/"
[[params.social]]
    name = "Mail"
    icon = "fas fa-envelope fa-2x"
    weight = 4
    url = "mailto:cjt.jackton@gmail.com"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 1
            url = "/posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 2
            url = "/projects/"

            [[languages.en.menu.main]]
            name = "About"
            weight = 3
            url = "/about/"

    [languages.zh-cn]
        languagename = "ä¸­æ–‡"
        dateformat = "2006 å¹´ 1 æœˆ 2 æ—¥"

        [languages.zh-cn.params]
            author = "CJT"
            info = "ä¸€ä¸ªå…´è¶£ä½¿ç„¶çš„ç¨‹åºå‘˜"
            description = "CJT ä¸ªäººä¸»é¡µ"
            keywords = "blog,developer,personal"
            footercontent = "å—¯ï¼Œocï¼"

        [languages.zh-cn.menu]

            [[languages.zh-cn.menu.main]]
            name = "åšæ–‡"
            weight = 1
            url = "/posts/"

            [[languages.zh-cn.menu.main]]
            name = "é¡¹ç›®"
            weight = 2
            url = "/projects/"

            [[languages.zh-cn.menu.main]]
            name = "å…³äº"
            weight = 3
            url = "/about/"

    [languages.ja]
        languagename = "æ—¥æœ¬èª"
        title = "Chinese tea ~ ä¸Šæµ·ç´…èŒ¶é¤¨"
        dateformat = "2006 å¹´ 1 æœˆ 2 æ—¥"

        [languages.ja.params]
            author = "CJT"
            info = "è¶£å‘³ã§ãƒ—ãƒ­ã‚°ãƒ©ãƒãƒ¼ã‚’ã‚„ã£ã¦ã„ã‚‹è€…ã "
            description = "CJTã®ã‚µã‚¤ãƒˆ"
            keywords = "blog,developer,personal"
            footercontent = "ãŠè“å­ã‚ˆï¼ã“ã®é…’é£²ã¿ãŒï¼"

        [languages.ja.menu]

            [[languages.ja.menu.main]]
            name = "ãƒ–ãƒ­ã‚°"
            weight = 1
            url = "/posts/"

            [[languages.ja.menu.main]]
            name = "ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆ"
            weight = 2
            url = "/projects/"

            [[languages.ja.menu.main]]
            name = "è‡ªå·±ç´¹ä»‹"
            weight = 3
            url = "/about/"