baseurl = "https://cjt-jackton.github.io/"
title = "Chinese tea ~ ä¸Šæµ·çº¢èŒ¶é¦†"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "CJT"
    info = "24 years old, is student."
    description = "CJT's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/images/favicon.ico"
    favicon_16 = "/images/favicon.ico"

    footercontent = "ğŸ° is a lie."

    dateformat = "January 2, 2006"

    hidecredits = false
    hidecopyright = false
    since = 2020

    rtl = false

    colorscheme = "dark"

    math = true

    custom_css = [ "/css/particles.css" ]
    custom_js = [ "/js/particles.js", "/js/app.js" ]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/cjt-jackton/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/CJT____________/"
[[params.social]]
    name = "Mail"
    icon = "fas fa-envelope fa-2x"
    weight = 3
    url = "mailto:cjt.jackton@gmail.com"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Post"
            weight = 1
            url = "/posts/"

            [[languages.en.menu.main]]
            name = "About"
            weight = 2
            url = "/about/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "/projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "/contact/"

    [languages.zh-cn]
        languagename = "ä¸­æ–‡"

        [languages.zh-cn.params]
            author = "CJT"
            info = "24å²ï¼Œæ˜¯å­¦ç”Ÿã€‚"
            description = "CJT ä¸ªäººä¸»é¡µ"
            keywords = "blog,developer,personal"
            footercontent = "å—¯ï¼Œocã€‚"

        [languages.zh-cn.menu]

            [[languages.zh-cn.menu.main]]
            name = "è‡ªæˆ‘ä»‹ç»"
            weight = 1
            url = "about/"

            [[languages.zh-cn.menu.main]]
            name = "åšæ–‡"
            weight = 2
            url = "posts/"

            [[languages.zh-cn.menu.main]]
            name = "é¡¹ç›®"
            weight = 3
            url = "projects/"

            [[languages.zh-cn.menu.main]]
            name = "è”ç»œ"
            weight = 5
            url = "contact/"

    [languages.ja]
        languagename = "æ—¥æœ¬èª"
        title = "Chinese tea ~ ä¸Šæµ·ç´…èŒ¶é¤¨"

        [languages.ja.params]
            author = "CJT"
            info = "24æ­³ã€å­¦ç”Ÿã§ã™ã€‚"
            description = "CJTã®ã‚µã‚¤ãƒˆ"
            keywords = "blog,developer,personal"
            footercontent = "ãŠè“å­ã‚ˆï¼ã“ã®é…’é£²ã¿ãŒï¼"

        [languages.ja.menu]

            [[languages.ja.menu.main]]
            name = "è‡ªåˆ†ç´¹ä»‹"
            weight = 1
            url = "about/"

            [[languages.ja.menu.main]]
            name = "ãƒ–ãƒ­ã‚°"
            weight = 2
            url = "posts/"

            [[languages.ja.menu.main]]
            name = "ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆ"
            weight = 3
            url = "projects/"

            [[languages.ja.menu.main]]
            name = "é€£çµ¡"
            weight = 5
            url = "contact/"